name: tbd-env
channels:
 - conda-forge
 - pytorch
dependencies:
  - python=3.6
  - numpy=1.13.3
  - matplotlib=2.0
  - h5py=2.7
  - pathlib2=2.3
  - scipy=0.19.1
  - torchvision
  - pytorch=0.4.1
  - typing
  - scikit-image
  - six
  - pillow
  - configobj
